# Generated by Django 4.1.3 on 2022-11-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weatherapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailsubscription",
            name="is_subscribed",
            field=models.BooleanField(default=True),
        ),
    ]
